name: BigDoors2
main: nl.pim16aap2.bigdoors.spigot.BigDoorsPlugin
version: ${project.version}
author: pim16aap2
api-version: 1.19
libraries:
  - it.unimi.dsi:fastutil:${dependency.version.fastutil}
  - com.alibaba:fastjson:${dependency.version.fastjson}
