package nl.pim16aap2.animatedarchitecture.core.localization;

import nl.pim16aap2.testing.annotations.FileSystemTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.FileSystem;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipOutputStream;

@ExtendWith(MockitoExtension.class)
class LocalizationGeneratorIntegrationTest
{
    private static final String BASE_NAME = "Translation";
    private static final String BASE_NAME_A = "Translation-A";
    private static final String BASE_NAME_B = "Translation-B";

    private static final List<String> INPUT_A_0 =
        List.of("a_key0=val0", "a_key1=val1", "a_key2=val2", "a_key3=val3", "a_key4=val4");

    private static final List<String> INPUT_A_1 =
        List.of("b_key0=val0", "b_key1=val1", "b_key2=val2", "b_key3=val3", "b_key4=val4");

    private static final List<String> INPUT_B_0 =
        List.of("a_key3=val100", "a_key4=val101", "a_key5=val102", "a_key6=val103", "a_key7=val104");

    @FileSystemTest
    void testAddResourcesFromJar(Path rootDirectory)
        throws IOException, URISyntaxException
    {
        final Path directoryOutput = Files.createDirectory(rootDirectory.resolve("output"));
        final Path directoryInput = Files.createDirectory(rootDirectory.resolve("input"));
        final Path jarFile = Files.createFile(directoryInput.resolve("test.jar"));
        createJar(jarFile).close();

        final LocalizationGenerator localizationGenerator = new LocalizationGenerator(directoryOutput, BASE_NAME);
        localizationGenerator.addResourcesFromZip(jarFile, null);

        verifyJarOutput(directoryOutput);
    }

    @FileSystemTest
    void testApplyPatches(Path rootDirectory)
        throws IOException, URISyntaxException
    {
        final Path directoryOutput = Files.createDirectory(rootDirectory.resolve("output"));
        final Path jarFile = Files.createFile(directoryOutput.resolve(BASE_NAME + ".bundle"));
        final Map<String, String> patches = new LinkedHashMap<>();
        patches.put("a_key0", "a_key0= ");
        patches.put("a_key10", "a_key10=a_a_a_a");

        final ZipOutputStream outputStream = new ZipOutputStream(Files.newOutputStream(jarFile));
        LocalizationTestingUtilities.writeEntry(outputStream, BASE_NAME + ".properties", INPUT_A_0);
        outputStream.close();

        final LocalizationGenerator localizationGenerator = new LocalizationGenerator(directoryOutput, BASE_NAME);
        localizationGenerator.applyPatches("", patches);
        localizationGenerator.applyPatches("en_US", patches);

        final FileSystem fileSystem = LocalizationTestingUtilities.createFileSystem(
            directoryOutput.resolve(BASE_NAME + ".bundle"));

        final List<String> linesBase =
            LocalizationUtil.readFile(Files.newInputStream(fileSystem.getPath(BASE_NAME + ".properties")));

        Assertions.assertEquals(
            List.of(
                "a_key0= ",
                "a_key1=val1",
                "a_key2=val2",
                "a_key3=val3",
                "a_key4=val4",
                "a_key10=a_a_a_a"),
            linesBase
        );

        // The en_US file did not exist in the output bundle, so it should contain only the patches.
        final List<String> linesEnUS =
            LocalizationUtil.readFile(Files.newInputStream(fileSystem.getPath(BASE_NAME + "_en_US.properties")));
        Assertions.assertEquals(List.of("a_key0= ", "a_key10=a_a_a_a"), linesEnUS);
    }

    /**
     * Verifies that the files generated by the {@link LocalizationGenerator} based on the jar created with
     * {@link #createJar(Path)} are correct.
     *
     * @param directoryOutput
     *     The output directory where the jar file is located.
     */
    private void verifyJarOutput(Path directoryOutput)
        throws IOException, URISyntaxException
    {
        try (
            FileSystem outputFileSystem =
                LocalizationTestingUtilities.createFileSystem(directoryOutput.resolve(BASE_NAME + ".bundle")))
        {
            final Path outputFile0 = outputFileSystem.getPath(BASE_NAME + ".properties");
            final Path outputFile1 = outputFileSystem.getPath(BASE_NAME + "_en_US.properties");

            Assertions.assertTrue(Files.exists(outputFile0));
            Assertions.assertTrue(Files.exists(outputFile1));

            Assertions.assertEquals(INPUT_B_0, LocalizationUtil.readFile(Files.newInputStream(outputFile1)));

            final List<String> outputBase = new ArrayList<>(10);
            outputBase.addAll(INPUT_A_0);
            outputBase.addAll(INPUT_A_1);
            Assertions.assertEquals(outputBase, LocalizationUtil.readFile(Files.newInputStream(outputFile0)));
        }
    }

    /**
     * Creates a jar file with three locale files.
     *
     * @param jarFile
     *     An (existing) jar file.
     * @return The {@link ZipOutputStream} with the jar file. This can be used to append more data. Don't forget to
     * close this.
     */
    private ZipOutputStream createJar(Path jarFile)
        throws IOException
    {
        final ZipOutputStream outputStream = new ZipOutputStream(Files.newOutputStream(jarFile));
        LocalizationTestingUtilities.writeEntry(outputStream, BASE_NAME_A + ".properties", INPUT_A_0);
        LocalizationTestingUtilities.writeEntry(outputStream, BASE_NAME + ".properties", INPUT_A_1);
        LocalizationTestingUtilities.writeEntry(outputStream, BASE_NAME_B + "_en_US.properties", INPUT_B_0);
        return outputStream;
    }
}
