name: AnimatedArchitecture
main: nl.pim16aap2.animatedarchitecture.spigot.core.AnimatedArchitecturePlugin
version: ${project.version}
author: pim16aap2
api-version: 1.19
libraries:
  - it.unimi.dsi:fastutil:${dependency.version.fastutil}
  - com.alibaba:fastjson:${dependency.version.fastjson}
  - net.bytebuddy:byte-buddy:${dependency.version.bytebuddy}
  - com.google.flogger:flogger:${dependency.version.flogger}
  - com.google.flogger:flogger-log4j2-backend:${dependency.version.flogger}
