name: AnimatedArchitecture
main: nl.pim16aap2.animatedarchitecture.spigot.core.AnimatedArchitecturePlugin
version: ${project.version}
author: pim16aap2
api-version: 1.20
depend:
  - Vault
libraries:
  - it.unimi.dsi:fastutil:${dependency.fastutil.version}
  - com.alibaba:fastjson:${dependency.fastjson.version}
  - net.bytebuddy:byte-buddy:${dependency.bytebuddy.version}
  - org.flywaydb:flyway-core:${dependency.flyway.version}
