name: AnimatedArchitecture
main: nl.pim16aap2.animatedarchitecture.spigot.core.AnimatedArchitecturePlugin
version: ${project.version}
author: pim16aap2
api-version: 1.20
depend:
  - Vault
libraries:
  - it.unimi.dsi:fastutil:${version.fastutil}
  - com.alibaba:fastjson:${version.fastjson}
  - net.bytebuddy:byte-buddy:${version.bytebuddy}
  - org.flywaydb:flyway-core:${version.flyway}
  - com.google.flogger:flogger:${version.flogger}
  - com.google.flogger:flogger-log4j2-backend:${version.flogger}
  - com.google.dagger:dagger:${version.dagger}
  - nl.pim16aap2.jcalculator:jcalculator:${version.jcalculator}
